### ISSUE TITLE
Error on game Load

### ISSUE THREAD

**Issue by Wolphin5** [appuns/DSPAllPlanetInfo#1]
![image](https://github.com/appuns/DSPAllPlanetInfo/assets/44385601/dce7bf4c-a699-49be-967f-f8cd91093dc0)

I don't get the message when the plugin is disabled, but get the error when it is loaded.

Game was working fine yesterday.  Appears an update did apply to the game overnight.
Current version 0.10.28.20779.

**Comment by Chemie99** [comment]
hoping appuns is still active as this is a great mod...but DF broke it.

**Comment by Wolphin5** [comment]
This update has been resolved by update 1.1.9
